[window.dimensions]
columns = 133
lines = 33

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Left", mods = "Control|Shift", action = "Copy" },
{ mouse = "Right", mods = "Control|Shift", action = "Paste" }
]

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "C", mods = "Control|Shift", action = "Copy" },
{ key = "V", mods = "Control|Shift", action = "Paste" },
{ key = "Q", mods = "Control|Shift", action = "Quit" },
{ key = "M", mods = "Control|Shift", action = "Minimize" }
]

[bell]
duration = 300

[colors.bright]
black = '#686868'
blue = '#73d0ff'
cyan = '#95e6cb'
green = '#bae67e'
magenta = '#d4bfff'
red = '#f28779'
white = '#ffffff'
yellow = '#ffd580'

[colors.cursor]
cursor = '#ffcc66'
text = '#1f2430'

[colors.normal]
black = '#191e2a'
blue = '#6dcbfa'
cyan = '#90e1c6'
green = '#a6cc70'
magenta = '#cfbafa'
red = '#ed8274'
white = '#c7c7c7'
yellow = '#fad07b'

[colors.primary]
background = '#1f2430'
foreground = '#cbccc6'

[colors.selection]
background = '#33415e'
text = '#cbccc6'
